### PR TITLE
Fix flake8 linter warnings and add a Travis config that runs flake8

### PR DESCRIPTION
**Pull request by edmorley**
This PR fixes flake8 linter warnings (flake8 is a combination of the pyflakes and pep8 linters and is frequently used by Python projects) and adds a Travis config that runs flake8 to prevent it from regressing.

Most of the diff is just whitespace changes - see the individual commit diffs and commit messages for a clearer view (I've listed which warnings are fixed in each commit message).

In the future if any tests were added for the Python code in this repo, we could add them to the Travis run too.

Once this merges, someone with admin rights to the repo will need to go to https://travis-ci.org/profile/mozilla-it and toggle the switch next to this repo.

CC @gdestuynder and @jdow.

### CODE REVIEW

**Comment by limed** [comment]
THANK YOU! this makes my eyes hurt less when I see this, at a glance it looks good but I will wait for @jdow and @gdestuynder  to weigh in on this.

**Comment by edmorley** [comment]
You're welcome :-)

**Comment by floatingatoll** [comment]
++ to the flake8 parts, no opinion on the Travis parts

**Comment by edmorley** [comment]
Treeherder's .travis.yml for comparison:
https://github.com/mozilla/treeherder/blob/9bfd311ee862a05cdcabb7e14b8ce5a56d6639b5/.travis.yml#L21

**Comment by gdestuynder** [comment]
PEP8 does indicate that you may use tabs if the original project uses tabs though. This kind of changes are nice but ultimately lead to tenuous reviews - since the entire code has to be checked and read against the original. I did my best though and it looks right to me!

**Comment by edmorley** [comment]
> ultimately lead to tenuous reviews - since the entire code has to be checked and read against the original

When viewing commit by commit (or using diff viewer of choice, locally) the whitespace changes are marked so you can see there are no actual code changes.

> I did my best though and it looks right to me!

Thank you :-)

**Comment by edmorley** [comment]
Could someone with admin rights please toggle the switch next to this repo on https://travis-ci.org/profile/mozilla-it - thanks :-)

**Comment by limed** [comment]
@edmorley done

**Comment by edmorley** [comment]
Thanks! Nothing will show up until the next PR/push/... but it should all work at that point :-)

**Pull request merged**
